config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:new, :create, :show ] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_length_of :comment, minimum: 6
  validates_uniqueness_of :movie, scope: :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new

  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
    @list = List.new
  end


  def show
    @list = List.find(params[:id])
  end

  def new
  @list = List.new
  end

  def create

    @list = List.new(list_params)
    if @list.save
    redirect_to list_path(@list)

    else
      render :new, status: :unprocessable_entity
    end
  end

private

def list_params
  params.require(:list).permit(:name, :photo)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class = "container">

<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :comment %>
<%= f.association :movie %>
<%= f.submit class:"btn btn-primary" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

   <nav class="d-flex justify-content-between bg-light p-3">
     <div >
     <%= link_to "CINEMA", lists_path, class:"h5 text-decoration-none " %>
     </div>

      <div>
     <%= link_to "Nouvelle liste", new_list_path%>
    </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/lists/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Nouvelle liste</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for (@list) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i0.wp.com/www.acap-cinema.com/wp-content/uploads/2020/01/annuaire-des-salles.jpg?fit=2133%2C1200&ssl=1);">
  <div class="container">
    <h1>Ca va  <strong>listzer</strong> all <strong>night long</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Nouvelle liste
    </button>
    <%= render "modal" %>
  </div>

</div>


<div class="container">
<h1>Listes</h1>

<div class = "cards">
  <% @lists.each do |list|%>

  <%= link_to list_path(list) do %>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
        <%= list.name %>
    </div>
    <% end %>
    <% end %>

</div>

</div>

app/views/lists/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center ">
    <div class="col-6">
      <h2>Créer une nouvelle liste</h2>

      <%= simple_form_for (@list) do |f| %>
              <%= f.input :name %>
              <%= f.input :photo, as: :file %>
              <%= f.submit class:"btn btn-primary" %>
              <% end %>

    </div>

  </div>

</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>


  <div class = "row mt-2">

    <% @list.movies.each do |movie|  %>
      <div class="col-3">

        <div class="card w-100" style="width: 18rem;">
          <img class="card-img-top h-75" src="<%=movie.poster_url%>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"> <%= movie.title %></h5>
            <p class="card-text"> <%= movie.overview %></p>

          </div>
            <%= link_to "Retirer", list_bookmark_path(movie), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:'badge text-bg-secondary' %>
        </div>

      </div>

    <% end %>
  </div>


  <%= link_to "ajouter un film", new_list_bookmark_path(@list) %>
</div>